### PR TITLE
swift 4 support

### PR DESCRIPTION
**Pull request by vladislav-m**
@objc attribute was added to selector_panGesture to enable compilation for swift 4

### CODE REVIEW

**Comment by sovata8** [comment]
Thanks for your pull request.
This change was long overdue, so thanks for contributing.

Before merge your pull request, can you please look at the following:

I just tried performing the Swift 4 conversion myself, and along with the `@objc` addition in front of one of the functions, I also see five other changes, all in the `RevealingTableViewCell.xcodeproj/project.pbxproj` file:
- `LastSwiftMigration = 0830;` becomes `LastSwiftMigration = 0920;`
- In `Debug` target Build settings:
    - `SWIFT_VERSION` changes from `3.0` to `4.0`
    - New line is added: `SWIFT_SWIFT3_OBJC_INFERENCE = Default;`
- In `Release` target Build settings: same changes as in `Debug`

Not sure how you did the migration on your side, but I can't see these changes in your Pull Request, and they are important. So can you please make sure you do the migration completely?

Thanks

**Comment by sovata8** [comment]
@vladislav-m , please respond to the above - or alternatively, in one week, I will do the full conversion to Swift 4 directly on the repo and close this PR. Thanks.

**Comment by vladislav-m** [comment]
@sovata8 , sorry for late response, I was busy these days. Indeed I just fixed compiler errors and updated pod-related files manually, so the proper way for doing this would be to convert project with xcode. I'll do these changes today.

**Comment by vladislav-m** [comment]
@sovata8 , I came across some travis troubles during migration, not sure what exactly went wrong, need to research. And probably I'll do that on weekend. Feel free to convert and update travis settings properly on your side, if you have time for that.

**Comment by sovata8** [comment]
Closed because it's implemented on main now.

**Pull request closed without merging**
